/*
ESTE MOCK SERÁ UTILIZADO PARA CREAR UNA BASE DE DATOS DE FORMA LOCAL PARA EMULAR LA FUNCION DE LA APLICACION
1. SE DECLARA EXPORTS PARA QUE PUEDA SALIR SER USADA POR OTROS COMPONENTES.
1.1 DE DECLARA UNA VARIABLE QUE CONTIENE UN ARRAY DE OBJETOS DE TIPO CONSTANTES 
2. AHORA SE DEBE CREAR OTRO ARCHIVO PARA VINCULARLO CON ESTE. SUGERIBLE QUE EL NOMBRE SEA IGUAL AL DEL MOCK PERO SIN EL PREFIJO MOCK

3. SE IMRPOTA EL ARCHIVO DONDE ESTA DEFINIDO LA INTERFACE QUE TIENE LOS DATOS DEFINIDOS.

NOTA: ESTE MOCK CON EL ARREGLO DE OBJETO Y LA INTERFACE QUE SE CREO ES PARA QUE LOS DATOS A MANEJAR SEAN CONSISTENTES
*/

import {Task} from "./TASK";
    // A LA VARIABLE TASK SE LE DIDE QUE ES DE TIPO INTERFACE ( TASK: Task[]). SE PONE CORCHETES PORQUE ES UN ARRAY DE OBJETOS.
export const TASK: Task[]=[
{
    id:1,
    title:"Task 1",
    description:"Description 1",
    day:"Abril 5 a las 12:00",
    reminder:true,

},
{
    id:2,
    title:"Task 2",
    description:"Description 2",
    day:"Abril 6 a las 13:00",
    reminder:false,

}
]