/*
 ACA SE A CREAR LAS FUNCIONES Y SE ESPECIFICAN EL TIPO DE DATOS QUE LE VAMOS A PASAR.
 1. SE CREA UNA INTERFACE Y SE DECLARA EXPORT Y SE LE PASA UN NOMBRE. SUGERIBLE EL PROPIO NOMBRE DEL ARCIVO.
2. SE DECLARA LOS MISMAS VARIABLES CON SUS TIPOS DE DATOS .

NOTA: LO QUE HACE ESTA INTERFACE ES PREDETERMINAR EL TIPO DE DATO QUE DEBE USARSE EN EL MOCK. SON COMO REGLAS .

. ESTE ARCHIVO SE VA A DECLARAR COMO IMPOTAR EN EL MOCK DE TASK.TS
*/
export interface Task {
    id?: number;
    title: string;
    description: string;
    day: string;
    reminder: boolean;
}